[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "NODE_ENV=production node dist/main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[deploy.env]
NODE_ENV = "production"
PORT = "4000" 